name: Cypress ui api tests CBA SDIT

on: 
  workflow_dispatch:
  push:

jobs:
  install-ubuntu-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          runTests: false

  test-ubuntu-chrome:
    runs-on: ubuntu-latest
    needs: install-ubuntu-chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome

  install-windows-firefox:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          runTests: false

  test-windows-firefox:
    runs-on: windows-latest
    needs: install-ubuntu-chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: firefox
